<?php

/**
 * @file
 * Form options attributes module.
 */

use Drupal\Core\Template\Attribute;
use Drupal\Core\Render\Element\RenderElement;
use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function form_options_attributes_theme() {
  return [
    'form_options_attributes__select__options_attributes' => [
      'render element' => 'elements',
      'base hook' => 'select',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function form_options_attributes_theme_suggestions_select_alter(array &$suggestions, array $variables) {
  if (!empty($variables['element']['#options_attributes'])) {
    array_push($suggestions, 'form_options_attributes__select__options_attributes');
  }
}

/**
 * Implements hook_element_info_alter().
 */
function form_options_attributes_element_info_alter(array &$info) {
  $info['checkboxes']['#process'][] = 'form_options_attributes_form_process_option_attributes';
  $info['radios']['#process'][] = 'form_options_attributes_form_process_option_attributes';
}

/**
 * Prepares variables for select element templates.
 */
function form_options_attributes_preprocess_form_options_attributes__select__options_attributes(&$variables) {
  $element = $variables['element'];
  Element::setAttributes($element, ['id', 'name', 'size']);
  RenderElement::setAttributes($element, $variables['attributes']['class']);

  $variables['attributes'] = $element['#attributes'];
  $variables['options'] = form_select_options($element);

  foreach ($element['#options'] as $key => $option) {
    if (is_array($option)) {
      // This option in an opt group.
      foreach ($option as $sub_key => $sub_option) {
        if (!empty($element['#options_attributes'][$key][$sub_key])) {
          $attributes = $element['#options_attributes'][$key][$sub_key];
          $variables['options_attributes'][$key][$sub_key] = new Attribute($attributes);
        }
      }
    }
    elseif (!empty($element['#options_attributes'][$key])) {
      // This is a normal option with attributes set.
      $attributes = $element['#options_attributes'][$key];
      $variables['options_attributes'][$key] = new Attribute($attributes);
    }
  }
}

/**
 * Processes a checkboxes or radios form element to add options_attributes.
 *
 * Adds options_wrapper_attributes and options_label_attributes
 * along with the regular attributes.
 *
 * @param array $element
 *   Radios or checkboxes Form element.
 *
 * @return array
 *   Element with the new custom attributes.
 */
function form_options_attributes_form_process_option_attributes(array $element) {
  // Maps custom attribute keys to real render API attribute keys.
  $attributesTypesMap = [
    '#options_attributes'         => '#attributes',
    '#options_wrapper_attributes' => '#wrapper_attributes',
    '#options_label_attributes'   => '#label_attributes',
  ];
  foreach (Element::children($element) as $key) {
    // For each attribute type merge the custom attributes
    // with the parent's real attributes.
    foreach ($attributesTypesMap as $attributesType => $realAttributesType) {
      if (!empty($element[$attributesType][$key]) && is_array($element[$attributesType][$key])) {
        if (!empty($element[$key][$realAttributesType][$key]) && is_array($element[$key][$realAttributesType][$key])) {
          $element[$key][$realAttributesType] = array_merge($element[$key][$realAttributesType], $element[$attributesType][$key]);
        }
        else {
          $element[$key][$realAttributesType] = $element[$attributesType][$key];
        }
      }
    }
  }

  return $element;
}
