# Schema file for the configuration files of the addtoany module.
addtoany.settings:
  type: config_object
  label: 'AddToAny Settings'
  mapping:
    buttons_size:
      type: integer
    additional_html:
      type: text
      label: 'Additional HTML'
    additional_css:
      type: string
      label: 'Additional CSS'
    additional_js:
      type: string
      label: 'Additional JS'
    universal_button:
      type: string
      label: 'Universal Button Type'
    custom_universal_button:
      type: uri
      lable: 'Custom button URL'
    universal_button_placement:
      type: string
      label: 'Universal Button Placement'
    entities:
      type: sequence
      label: 'Entities'
      sequence:
        type: integer
        label: 'Status'

addtoany.block_base_settings:
  type: block_settings
  mapping:
    buttons_size:
      type: integer
    addtoany_html:
      type: string

block.settings.addtoany_block:
  type: addtoany.block_base_settings
  mapping:
    link_url:
      type: uri
    link_title:
      type: label
block.settings.addtoany_follow_block:
  type: addtoany.block_base_settings
