/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function ($, Drupal) {
  $.extend(Drupal.theme, {
    toggleButtonContent: function toggleButtonContent(show) {
      let classes = ['action-link', 'action-link--extrasmall', 'tabledrag-toggle-weight'];
      let icon = '';
      let title = '';
      if (show) {
        classes.push('action-link--icon-hide');
        title = Drupal.t('Hide row weights');
        icon = '<i class="bi bi-eye"></i>';
      } else {
        classes.push('action-link--icon-show');
        title = Drupal.t('Show row weights');
        icon = '<i class="bi bi-eye-slash"></i>';
      }
      return "<span class=\"".concat(classes.join(' '), "\" title=\"", title, "\">").concat(icon, "</a>");
    },
  });
})(jQuery, Drupal);
